=== Dariocastillo94/EjerciciosLenguajedeMarcas/Examen.dtd
<!ELEMENT registroMedicos (registro,hospital,observaciones)>
<!ELEMENT hospital (#PCDATA)>
<!ELEMENT observaciones (#PCDATA)>
<!ELEMENT registro (paciente | medico)*>
<!ELEMENT paciente (diagnostico,tratamiento,fecha?,(vivo|muerto))>
<!ELEMENT diagnostico (#PCDATA)>
<!ELEMENT tratamiento (#PCDATA)>
<!ELEMENT fecha (#PCDATA|fechaSalida)*>
<!ELEMENT fechaSalida (#PCDATA)>
<!ELEMENT  vivo EMPTY>
<!ELEMENT  muerto EMPTY>
<!ELEMENT medico (especialidad)>
<!ELEMENT especialidad (#PCDATA)>
<!ATTLIST registroMedicos premiun  IDREFS #REQUIRED>
<!ATTLIST paciente codigo ID #REQUIRED
                    nombre CDATA #REQUIRED
                    apellidos CDATA #REQUIRED
                    altura CDATA #IMPLIED
                    peso CDATA #IMPLIED
                    codigoFamiliaridad IDREF #IMPLIED>
<!ATTLIST medico nombre CDATA #REQUIRED
                apellidos CDATA #REQUIRED
                    experiencia CDATA #FIXED "10 aÃ±os">  
<!ENTITY UGR "Doctorado en la Universidad de Granada">
<!ENTITY % atributoLocalizacion "ciudad CDATA #REQUIRED">
<!ATTLIST hospital %atributoLocalizacion;>

=== Dariocastillo94/EjerciciosLenguajedeMarcas/Examen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE registroMedicos SYSTEM "Examen.dtd">
<registroMedicos premiun="Pac Mar">
    <registro>
        <paciente nombre="Antonio" codigo="Pac" altura="1,78" peso="77kg" apellidos="Castro Mora" codigoFamiliaridad="Mar">
            <diagnostico>arrítmias</diagnostico>
            <tratamiento>tratamiento intravenoso y en observación</tratamiento>
            <fecha>10/06/2023</fecha>
            <vivo />
        </paciente>
        <paciente nombre="Marta" codigo="Mar" altura="1,60" peso="60kg" apellidos="Dorado Espinoza" codigoFamiliaridad="Pac">
            <diagnostico>traumatismos craneoencefálico</diagnostico>
            <tratamiento>anticoagulantes</tratamiento>
            <fecha>10/06/2023</fecha>
            <vivo />
        </paciente>
        <medico nombre="Alfonso" experiencia="10 años" apellidos="De la Cruz Campo">
            <especialidad>Cardiólogo y neurologo&UGR;</especialidad>
        </medico>
    </registro>
    <hospital ciudad="Córdoba">Reina sofía</hospital>
    <observaciones>Progresa según lo esperado</observaciones>
</registroMedicos>
